# syntax=docker/dockerfile:1

ARG UBUNTU_VERSION=24.04

FROM ubuntu:${UBUNTU_VERSION}

ARG PYTHON_VERSION=3.11
ARG DEBIAN_FRONTEND=noninteractive
ARG UID=10001

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_ROOT_USER_ACTION=ignore \
    USERNAME=runner \
    PLAYWRIGHT_BROWSERS_PATH=/app/pw-browsers

# Update & install essential packages:
#   software-properties-common: for add-apt-repository
#   curl, jq: for requesting Gmail access token
#   ca-certificates: for HTTPS requests (Gmail API, pip installs)
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    curl \
    jq \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Add deadsnakes PPA and install Python3.11
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && apt-get install -y --no-install-recommends \
    python${PYTHON_VERSION} \
    python${PYTHON_VERSION}-dev \
    python${PYTHON_VERSION}-distutils \
    python${PYTHON_VERSION}-venv \
    && rm -rf /var/lib/apt/lists/*

# Setup Python and pip
RUN <<EOF
curl -sS https://bootstrap.pypa.io/get-pip.py | python${PYTHON_VERSION}
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1
update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON_VERSION} 1
python3 --version
EOF

# Set working directory
WORKDIR /app

COPY requirements.txt pyproject.toml README.md ./
COPY src ./src/

# Use a virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install Python dependencies and chromium headless shell as root
RUN <<EOF
python3 -m pip install --no-cache-dir --upgrade pip
python3 -m pip install --no-cache-dir -r requirements.txt
python3 -m playwright install --with-deps --only-shell chromium
python3 -m pip install --no-cache-dir .
rm -rf /var/lib/apt/lists/*
EOF

COPY . .

RUN <<EOF
useradd -lMU -u ${UID} ${USERNAME}
chown -R ${USERNAME}:${USERNAME} /app
chmod +x ./docker/docker-entrypoint.sh
EOF

USER ${USERNAME}

ENTRYPOINT ["/app/docker/docker-entrypoint.sh"]
