name: clinictracker

services:
  run-task:
    image: clinic-test:run-py
    pull_policy: build
    build:
      context: .
      dockerfile: docker/Dockerfile-multi-py
      target: run
    container_name: clinic-run
    secrets:
      - gmail_api
    env_file:
      - ./.env
    environment:
      - TEST_MODE=false
      - KEEP_ALIVE=false
      - SEND_EMAILS=false
      - SECRETS_FILE=/run/secrets/gmail_api
    volumes:
      - ./output:/app/output

  test-mode:  # install browser and change user, but turn on test mode
    image: clinic-test:run-py
    pull_policy: build
    build:
      context: .
      dockerfile: docker/Dockerfile-multi-py
      target: run
    container_name: clinic-test
    secrets:
      - gmail_api
    env_file:
      - ./.env.test
    environment:
      - TEST_MODE=true
      - KEEP_ALIVE=false
      - SEND_EMAILS=false
      - SECRETS_FILE=/run/secrets/gmail_api
    volumes:
      - ./output:/app/output
    entrypoint: /bin/bash  # Override the ENTRYPOINT
    stdin_open: true  # Keep STDIN open (-i)
    tty: true  # Allocate a pseudo-TTY (-t)

  db:
    image: postgres:17.4-alpine
    container_name: clinic-db
    restart: always
    secrets:
      - pg_password
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d userservice"]
      interval: 5s
      timeout: 5s
      retries: 5

secrets:
  gmail_api:
    file: ./.secrets  # token and sender
  pg_password:
    file: ./.pg_password

volumes:
  pgdata:
