[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "clinictracker"
version = "0.1.2"
authors = [
    { name = "Lydia Zhang" },
]
description = "Fetches clinic updates across specified regions from a target website."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "beautifulsoup4>=4.13.5",
    "pytest-playwright>=0.7.1",
    "python-dateutil",
    "python-dotenv",
]

[project.scripts]
clinictracker = "clinictracker.cli:main"
clinictracker-user = "clinictracker.user.cli:main"

[project.urls]
"Homepage" = "https://github.com/lydiazly/clinic-updates-tracker"
"Bug Tracker" = "https://github.com/lydiazly/clinic-updates-tracker/issues"

[tool.pytest.ini_options]
addopts = "--browser-channel chromium -s"
testpaths = ["tests"]
