[tox]
env_list = py311,py312,min-versions
minversion = 4.0
requires = tox-uv

[testenv]
runner = uv-venv-lock-runner
groups = dev
description = run the tests with pytest
commands =
    pytest {tty:--color=yes} {posargs}

[testenv:min-versions]
runner = uv-venv-runner
description = Test with minimum supported dependency versions
deps =
    beautifulsoup4==4.13.5
    psycopg2-binary==2.9.10
    python-dateutil==2.9.0
    python-dotenv==1.2.0
    pytest-playwright==0.7.1
    pytest
    pytest-asyncio
commands =
    pytest {tty:--color=yes} {posargs}

[testenv:type]
runner = uv-venv-lock-runner
groups = dev
description = run type checker via mypy
commands =
    mypy {posargs:src}
