# syntax=docker/dockerfile:1

ARG UBUNTU_VERSION=24.04

FROM ubuntu:${UBUNTU_VERSION}

ARG DEBIAN_FRONTEND=noninteractive
ARG UID=10001

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_ROOT_USER_ACTION=ignore \
    USERNAME=runner \
    PLAYWRIGHT_BROWSERS_PATH=/app/pw-browsers

# Update & install essential packages & python3.12:
#   curl, jq: for requesting Gmail access token
#   ca-certificates: for HTTPS requests (Gmail API, pip installs)
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    jq \
    ca-certificates \
    python3 python3-pip python3-venv \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./requirements.txt ./src ./pyproject.toml ./README.md ./

# Use a virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install Python dependencies and chromium headless shell as root
RUN <<EOF
python3 -m pip install --no-cache-dir --upgrade pip
python3 -m pip install --no-cache-dir -r requirements.txt
python3 -m playwright install --with-deps --only-shell chromium
python3 -m pip install --no-cache-dir .
rm -rf /var/lib/apt/lists/*
EOF

COPY . .

RUN useradd -lMU -u ${UID} ${USERNAME} \
    && chown -R ${USERNAME}:${USERNAME} /app \
    && chmod +x ./docker/docker-entrypoint.sh

USER ${USERNAME}

ENTRYPOINT ["/app/docker/docker-entrypoint.sh"]
