[dev]  # connect Docker db from Docker
host=db
port=5432
dbname=userservice
user=admin

[dev-local]  # connect Docker db from host
host=localhost
port=5432
dbname=userservice
user=admin

[prod]  # Neon
host=ep-mute-rice-afybsmkx-pooler.c-2.us-west-2.aws.neon.tech
port=5432
dbname=userservice
user=neondb_owner
sslmode=require
channel_binding=require
